name: Push
on:
  push:
    branches:
      - draft
  pull_request:
    branches:
      - "**"
permissions:
  contents: read
jobs:
  Linux_x86_64:
    name: 'Linux x86_64'
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    env:
      CFLAGS: '-fsanitize=address,undefined'
    steps:
      - uses: actions/checkout@v5
      - name: apt
        run: |
          apt update -y
          DEBIAN_FRONTEND=noninteractive apt install -y \
            gcc \
            libcapstone-dev \
            libcapstone4 \
            make
      - name: git checkout ir
        uses: actions/checkout@v5
        with:
          repository: dstogov/ir
          path: ir
      - name: make ir
        run: |
          cd ir
          make TARGET=x86_64 BUILD=debug all
          make TARGET=x86_64 BUILD=debug install
      - name: make
        run: make TARGET=x86_64 BUILD=debug all
      - name: test
        run: make TARGET=x86_64 BUILD=debug test-ci
  Linux_aarch64:
    name: 'Linux aarch64'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: git checkout ir
        uses: actions/checkout@v5
        with:
          repository: dstogov/ir
          path: ir
      - uses: uraimo/run-on-arch-action@v2
        name: QEMU
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt update -y
            DEBIAN_FRONTEND=noninteractive apt install -y \
              gcc \
              libc6 \
              libcapstone-dev \
              libcapstone4 \
              make
          run: |
            cd ir
            make CC=gcc TARGET=aarch64 BUILD=debug all
            make CC=gcc TARGET=aarch64 BUILD=debug install
          run: |
            make CC=gcc TARGET=aarch64 BUILD=debug all
            # FIXME: For some reason some of the object files are rebuilt
            make CC=gcc TARGET=aarch64 BUILD=debug test-ci
